package app.lineo.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Turns the shipped licence allowlist into the list the attribution screen renders.
 *
 * Apache-2.0 §4 requires a copy of the licence to travel with the binary, and MIT and BSD
 * require the copyright notice. That obligation applies to what is *distributed*, which is
 * exactly what `config/licenses/allowed-dependencies.txt` records after the shipped and
 * test-only lists were split.
 *
 * Generating from that file rather than from a separate scan is the point. The build already
 * fails when a shipped dependency is missing from it, so the attribution cannot fall behind
 * what actually ships: a new library has to be recorded before the build passes, and once
 * recorded it appears on the screen without anyone remembering to add it.
 *
 * The output is a Kotlin source file rather than an asset so that reading it needs no
 * `Context` — `docs/ANDROID_STANDARDS.md` §1 keeps those out of the layers above the data
 * one, and a list of strings compiled into the binary has nothing to open or parse.
 */
abstract class GenerateLicenseAttributionTask : DefaultTask() {
    init {
        group = "build"
        description = "Generates the open-source attribution list from the shipped licence allowlist."
    }

    @get:InputFile
    abstract val allowlist: RegularFileProperty

    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val entries = allowlist.get().asFile.readLines()
            .map { it.trim() }
            .filter { it.isNotEmpty() && !it.startsWith("#") }
            .map { line ->
                val module = line.substringBefore("#").trim()
                val licence = line.substringAfter("#", missingDelimiterValue = "").trim()
                Entry(module, licence)
            }
            .sortedBy { it.module }

        if (entries.isEmpty()) {
            throw GradleException("The shipped licence allowlist is empty; the attribution screen would ship blank.")
        }
        requireCopyrightWhereTheLicenceDemandsIt(entries)

        val target = outputDirectory.get().asFile.resolve(PACKAGE_PATH).apply { mkdirs() }
        target.resolve("GeneratedAttribution.kt").writeText(render(entries))
    }

    /**
     * MIT and BSD both require the copyright line to travel with the binary; Apache-2.0 does
     * not. No shipped dependency needs one today, so rather than carry an empty column the
     * build refuses the first one that does — the notice has to be recorded before it ships,
     * which is the only moment anyone will know where to find it.
     */
    private fun requireCopyrightWhereTheLicenceDemandsIt(entries: List<Entry>) {
        val missing = entries.filter { entry ->
            val head = entry.licence.substringBefore("(").trim()
            (head.startsWith("MIT") || head.startsWith("BSD")) && !entry.licence.contains(COPYRIGHT_MARKER)
        }
        if (missing.isNotEmpty()) {
            throw GradleException(
                buildString {
                    appendLine("These shipped dependencies are MIT or BSD, which require their copyright notice:")
                    missing.forEach { appendLine("  ${it.module}") }
                    appendLine()
                    appendLine("Record it in the allowlist entry, for example:")
                    appendLine("  group:name  # MIT $COPYRIGHT_MARKER 2019 Example Author")
                },
            )
        }
    }

    private fun render(entries: List<Entry>): String = buildString {
        appendLine("// Generated by :app:generateLicenseAttribution. Do not edit.")
        appendLine("// Source: config/licenses/allowed-dependencies.txt")
        appendLine("package $PACKAGE_NAME")
        appendLine()
        appendLine("internal val GENERATED_ATTRIBUTION: List<LicensedDependency> = listOf(")
        entries.forEach { entry ->
            appendLine("    LicensedDependency(")
            appendLine("        module = \"${entry.module}\",")
            appendLine("        licence = \"${entry.licence.escaped()}\",")
            appendLine("    ),")
        }
        appendLine(")")
    }

    private fun String.escaped(): String = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\${'$'}")

    private data class Entry(val module: String, val licence: String)

    private companion object {
        const val PACKAGE_NAME = "app.lineo.licenses"
        const val PACKAGE_PATH = "app/lineo/licenses"

        /** What an allowlist entry writes before a copyright holder. */
        const val COPYRIGHT_MARKER = "Copyright"
    }
}
